### ISSUE TITLE
Nick - Intro Pass

### ISSUE THREAD

**Issue by Chasexj** [noise-lab/nsdi_llm_config#1]

**Comment by feamster** [comment]
* Context and token overload should be better explained.
* Should define focus and coverage.
* "In this paper ..." paragraph should be more direct about what specific problem is being solved. Is it figuring out the right amount of context to include? I want to know right away (first sentence in this para) what specific intellectual/research problem you are addressing, not just the thing you built.
* Network configurations are actually not that big compared to many types of text, so I'm a little unclear on Challenge 1.
* Need more detail on why breaking things down into three types of context is so helpful. The existence of hierarchy doesn't automatically prevent incorporating irrelevant information into the configuration file.
* I don't understand the change detection use case. How does that relate to misconfiguration?
* The claim about "outperforming" existing methods is really vauge. Which methods?! By how much?! How did you conclude this (what was the experiment)?
