### ISSUE TITLE
Nick - Method Pass

### ISSUE THREAD

**Issue by Chasexj** [noise-lab/nsdi_llm_config#3]

**Comment by feamster** [comment]
* Explain more explicitly the limitations of partition-based prompting at the beginning, or make that more explicit in the previous section with a heading. Section starts off a bit abruptly, without... "context". :-)
* The context overload issue is explained quite a few times (repetition).
* The observations should be presented/structured as sentences for the observations themselves. (right now they don't read like observations)
* Maybe provide an example of each type of configuration. Right now it is rather abstract.
* Same comment on the iterative prompting process. I read it and think not only is the method clear, but also it is clear why it works. That being said, I'd love to see a brief example of the prompting sequence for a particular case where it does well. That concreteness would really bring this to life.

Overall, nice writeup!
